shared_script '@BRPS-GUARD/ai_module_fg-obfuscated.lua'
shared_script '@BRPS-GUARD/shared_fg-obfuscated.lua'
fx_version 'cerulean'
game 'gta5'
lua54 'yes'
author 'Kakarot'
description 'Allows players to rob specific trucks for money and items'
version '1.2.0'
shared_script 'config.lua'
server_script 'server/main.lua'
client_script 'client/main.lua'
