var questions = {
    ['A']: [
        {
            "questionPhoto": 'question_1.png',
            "question": 'Can you drive on the public road in this manner?',
            "a": 'Yes, if there are no other vehicles nearby.',
            "b": 'No.',
            "c": 'Yes, if you are confident in your skills.',
            "d": 'Yes, only outside urban areas.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'question_2.png',
            "question": 'When approaching the center of a turn, you should',
            "a": 'move to the outside of the curve.',
            "b": 'decrease the throttle.',
            "c": 'move to the inside of the curve.',
            "d": 'apply the rear brake.',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'question_3.png',
            "question": 'Approaching an intersection, you should choose a lane position to',
            "a": 'reduce your following distance.',
            "b": 'increase your visibility to other vehicle drivers.',
            "c": 'increase your speed and pass quickly.',
            "d": 'do all of the above.',
            "correctAnswer": 'B',
        },
        {
            "question": 'What are the conditions for wearing a helmet?',
            "a": 'Wearing a helmet is not mandatory when riding on city streets.',
            "b": 'All motorcyclists and passengers must wear a helmet at all times.',
            "c": 'Only passengers are required to wear a helmet.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Gripping the front brake or locking the rear brake',
            "a": 'Is the best way to stop in an emergency.',
            "b": 'Is the best way to slow down when the roads are wet.',
            "c": 'Can lock the brakes.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Motorcycle passengers should',
            "a": 'Sit as far forward as possible without crowding you.',
            "b": 'Put their feet down when the motorcycle is stopped.',
            "c": 'Not ride without a backrest.',
            "correctAnswer": 'A',
        },
        {
            "question": 'When riding with a group of motorcyclists, staggered formation',
            "a": 'Should be used when riding through curves.',
            "b": 'Is recommended at all times.',
            "c": 'Should not be used when entering or exiting a highway.',
            "correctAnswer": 'C',
        },
        {
            "question": 'You must activate the engine cut-off switch and squeeze the clutch when',
            "a": 'The throttle is stuck and you cannot release it.',
            "b": 'You are starting to lose control in a curve.',
            "c": 'The motorcycle starts to wobble.',
            "correctAnswer": 'A',
        },

        {
            "question": 'Before changing lanes on a multi-lane road, you must check',
            "a": 'the lane next to you and the far lane.',
            "b": 'only the far lane.',
            "c": 'your turn signal.',
            "d": 'only the lane next to you.',
            "correctAnswer": 'A',
        },
        {
            "question": 'When riding in a group, the best formation is the __ formation.',
            "a": 'In Y.',
            "b": 'Side by side.',
            "c": 'Staggered.',
            "d": 'In a V shape.',
            "correctAnswer": 'C',
        },
        {
            "question": 'When making a slow, tight turn, the motorcyclist should',
            "a": 'lean in the opposite direction of the motorcycle.',
            "b": 'lean forward over the motorcycle.',
            "c": 'lean in the same direction as the motorcycle.',
            "d": 'keep the body upright while leaning the motorcycle.',
            "correctAnswer": 'D',
        },
        {
            "question": 'If there is oncoming traffic and you are passing a line of parked cars, what lane position should you choose?',
            "a": 'Center',
            "b": 'Right',
            "c": 'Center or right',
            "d": 'Left',
            "correctAnswer": 'A',
        },
        {
            "question": 'Most of the stopping power for your motorcycle is provided by',
            "a": 'the rear brake.',
            "b": 'the front and rear brakes equally.',
            "c": 'the clutch.',
            "d": 'the front brake.',
            "correctAnswer": 'D',
        },
        {
            "question": 'If your motorcycle starts to wobble, the best thing to do is',
            "a": 'brake quickly.',
            "b": 'gradually close the throttle.',
            "c": 'grip the handlebars firmly and ride out the wobble.',
            "d": 'accelerate out of the wobble.',
            "correctAnswer": 'C',
        },
        {
            "question": "Surfaces that offer little traction for a motorcycle include",
            "a": 'lightly traveled lanes.',
            "b": 'gravel roads.',
            "c": 'tire marks, where other vehicles have traveled.',
            "d": 'road that is hot from the sun.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Increase your safety at night by',
            "a": 'using the headlights of the car in front to help you see.',
            "b": 'increasing your following distance.',
            "c": 'riding with your high beams on.',
            "d": 'doing all of the above.',
            "correctAnswer": 'D',
        },
        {
            "question": 'When following a vehicle, you should maintain a following distance of ___ seconds.',
            "a": 'two',
            "b": 'three',
            "c": 'four',
            "d": 'five',
            "correctAnswer": 'A',
        },
        {
            "question": 'In a traffic lane, how many lane positions are there for a motorcycle?',
            "a": '1',
            "b": '2',
            "c": '3',
            "d": '4',
            "correctAnswer": 'C',
        },
    ],
    ['B']: [
        {
            "questionPhoto": 'question_1.png',
            "question": 'Should you brake in this situation?',
            "a": 'Yes, because there is enough distance to brake.',
            "b": 'No, because the traffic light will turn green in a moment.',
            "c": 'No.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_2.png',
            "question": 'Can you stop on this part of the sidewalk?',
            "a": 'Yes, but only when the police stop us.',
            "b": 'Yes.',
            "c": 'Yes, for a maximum of 5 minutes.',
            "d": 'No.',
            "correctAnswer": 'D',
        },
        {
            "questionPhoto": 'question_3.png',
            "question": 'Can you make a left turn in this situation?',
            "a": 'Yes.',
            "b": 'No.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_4.png',
            "question": 'Can you turn right at this point without stopping?',
            "a": 'Yes, when vehicles are not coming from the left side.',
            "b": 'No, the sign requires the vehicle to stop completely.',
            "c": 'Yes, this sign means I have the right of way.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_5.png',
            "question": 'What is the maximum speed you can travel on this road?',
            "a": '140 km/h',
            "b": '110 km/h',
            "c": '120 km/h',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'question_6.png',
            "question": 'Can the road shown in the photo be traveled in both directions?',
            "a": 'Yes, if it does not compromise the safety of other traffic participants.',
            "b": 'No.',
            "c": 'Yes.',
            "d": 'Only taxis can travel in the opposite direction.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'question_7.png',
            "question": 'Can you make a left turn at this stage?',
            "a": 'Yes.',
            "b": 'No.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'question_8.png',
            "question": 'Which of these road markings separates two lanes traveling in the same direction?',
            "a": 'A',
            "b": 'B',
            "c": 'None of these answers',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'question_9.png',
            "question": 'This sign means:',
            "a": 'Pedestrian crossing ahead',
            "b": 'Pedestrians must not cross here',
            "c": 'Pedestrians walking along the road ahead',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_10.png',
            "question": 'This sign means:',
            "a": 'Do not enter.',
            "b": 'Parking reserved for disabled people.',
            "c": 'Yield.',
            "correctAnswer": 'A',
        },
        {
            "question": 'Can you overtake another vehicle when approaching a turn or hill?',
            "a": 'Yes, but you can only pass on the right.',
            "b": 'No, never.',
            "c": 'Yes, but only if there is enough space.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Which of the following places is a permissible U-turn?',
            "a": 'On a railroad crossing',
            "b": 'Across a double yellow line',
            "c": 'In a one-way street',
            "correctAnswer": 'B',
        },
        {
            "question": 'You should reduce your speed by half when the road is ___.',
            "a": 'wet',
            "b": 'icy',
            "c": 'snow-packed',
            "correctAnswer": 'C',
        },
        {
            "question": 'When driving in fog, rain, or snow, use ___.',
            "a": 'low beams',
            "b": 'fog lights only',
            "c": 'high beams',
            "correctAnswer": 'A',
        },
        {
            "question": 'A broken yellow centerline means:',
            "a": 'No passing is allowed.',
            "b": 'Passing on the left is allowed when the way ahead is clear.',
            "c": 'Passing on the right is allowed when the way ahead is clear.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Alcohol is',
            "a": 'A stimulant.',
            "b": 'Cool',
            "c": 'A depressant.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Before changing lanes, you should check your mirrors and',
            "a": 'Look over your shoulder',
            "b": 'Never look over your right shoulder',
            "c": 'Always slow down in your lane of travel',
            "correctAnswer": 'A',
        },
        
    ],
    ['C']: [
        {
            "question": 'Which of the following actions should you NOT do if you experience a tire failure?',
            "a": 'Be aware that a tire is failing.',
            "b": 'Brake hard and immediately.',
            "c": 'Hold the steering wheel firmly.',
            "d": 'Do not touch the brake pedal.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Flags or lights are required on projecting loads that extend',
            "a": '56 inches or more beyond the rear body.',
            "b": '3 feet or more beyond the rear body.',
            "c": '4 feet or more beyond the rear body.',
            "d": '6 feet or more beyond the rear body.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Which of these values corresponds to total stopping distance?',
            "a": 'Reaction distance + braking distance',
            "b": 'Reaction distance + braking distance + signaling distance',
            "c": 'Perception distance + reaction distance + braking distance',
            "d": 'Perception distance + reaction distance',
            "correctAnswer": 'C',
        },
        {
            "question": 'To help you stay alert and safe while driving, you should',
            "a": 'drink coffee if you are drowsy.',
            "b": 'avoid medications with warning labels mentioning drowsiness.',
            "c": 'take a shot of whiskey to prepare yourself.',
            "d": 'roll down your windows for fresh air.',
            "correctAnswer": 'B',
        },
        {
            "question": 'An A: B: C type fire extinguisher is designed to operate on which types of fires?',
            "a": 'Wood, paper, and fabric',
            "b": 'Gasoline',
            "c": 'Electric',
            "d": 'All of the above',
            "correctAnswer": 'D',
        },
    ],
}
